### PR TITLE
Preparing for release of v0.3.0

### PR DESCRIPTION
**Pull request by plokhotnyuk**
- Use the latest version of jsoniter-scala-core with fixes for remaining non-whitespace characters
- Add checking of binary compatibility for patch versions
- Add release plugin configuration
- Fix commented assertion
- Add more assertions
- Clean up docs

### CODE REVIEW

**Comment by plokhotnyuk** [comment]
So, now for release need:
- run the `sbt release` command 
- approve the release version
- enter password for signing
- wait until built artifacts will be uploaded to the Sonatype staging repo
- promote them on https://oss.sonatype.org/ to the release repo
- confirm pushing of local commits and a tag to the origin/master

**Comment by pathikrit** [comment]
WIll do!

**Comment by pathikrit** [comment]
I got:

image

**Comment by plokhotnyuk** [comment]
@pathikrit I've added missing `publishTo` in the following PR: https://github.com/pathikrit/dijon/pull/34

Please, check if it will work for you.

**Comment by pathikrit** [comment]
Done:
image

**Pull request merged**
